[workspace]
members = [
    "u-core",
    "u-io",
    "macros",
    "packets",
    "protocol",
    "network",
    "files",
    "framework",
    "examples/common",
    "examples/server",
    "examples/simple-server",
    "examples/proxy",
    "examples/simple-proxy",
    "examples/memory-proxy",
    "examples/client",
    "examples/data-files",
    "examples/web-proxy",
    "examples/replay-proxy",
    "examples/rpc-proxy",
    "examples/mirror-proxy",
    "examples/demo-server",
    "examples/benchmark",
    "examples/path-server",
    "examples/text-client",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
license = "MIT"
edition = "2024"
publish = false

