[package]
name = "protocol"

version = "0.1.0"
edition = "2024"
publish.workspace = true

[features]
proxy = ["tokio-socks"]

[dependencies]
u-core = { path = "../u-core" }
u-io = { path = "../u-io" }
packets = { path = "../packets" }
tokio = { version = "1.51.1", features = ["full"] }
tokio-socks = { version = "0.5", optional = true }
log = "0.4.29"
bytes = "1.11.1"
async-trait = "0.1.89"
