//! Kill-mobile operations: corpse creation, loot transfer, death events.
//!
//! The `handle_kill_mobile` function atomically:
//! 1. Reads the mobile's data (graphic, position, direction, equipment).
//! 2. Allocates serials for the corpse item and all loot items.
//! 3. Removes the living mobile from the zone store.
//! 4. Spawns the corpse as a persistent `DemoEntity::Item` with `is_container: true`.
//! 5. Registers the corpse in the container store with equipment + extra loot.
//! 6. Emits `WorldEvent::MobileKilled` (death animation + corpse clothing)
//!    and `WorldEvent::EntitySpawned` (persistent corpse for new observers).

use std::collections::HashMap;
use std::sync::Arc;

use framework::continuum::{ContainerContentChange, Zone, WorldEvent};
use framework::continuum::item_props::ZoneItemProps;
use framework::continuum::container::{ContainerInfo, ContainerItem, HashContainerStore, ZoneContainers};
use framework::ecumene::Entity as EngineEntity;

use crate::uo_engine::entity::DemoEntity;
use crate::uo_engine::item_props::{ItemProps, MetaValue};
use crate::uo_engine::serial_alloc::SerialAllocator;

use packets::layer::Layer;
use packets::world::EquippedItem;

// ── Public types ─────────────────────────────────────────────────────────

/// An additional loot item to place in the corpse container.
///
/// Equipment items are transferred automatically from the mobile.
/// This struct describes *extra* drops (gold, reagents, scrolls, etc.)
/// that are generated by loot tables.
#[derive(Debug, Clone)]
pub struct LootItem {
    /// Item graphic / artwork ID.
    pub graphic: u16,
    /// Item colour / hue (0 = default).
    pub color: u16,
    /// Stack amount.
    pub amount: u16,
    /// Optional display name override.
    pub name: Option<String>,
}

/// Result of a successful [`KillMobile`](super::EngineCommand::KillMobile)
/// command.
#[derive(Debug, Clone)]
pub struct KillResult {
    /// Serial allocated for the corpse item.
    pub corpse_serial: u32,
    /// Position where the corpse was placed.
    pub x: u16,
    pub y: u16,
    pub z: i8,
    /// The mount item (`Layer::Mount`) the player was riding at the moment of
    /// death, if any.  Removed from the player and NOT placed in the corpse:
    /// the caller (demo-server) re-spawns the original mount NPC beside the
    /// corpse.  Always `None` for `handle_kill_mobile`.
    pub dropped_mount: Option<EquippedItem>,
}

/// Corpse container gump model (UO classic).
const CORPSE_GUMP: u16 = 0x0009;

/// Corpse item graphic — used for all corpse types.
const CORPSE_GRAPHIC: u16 = 0x2006;

/// Layers that are cosmetic-only on the corpse and should NOT be lootable.
/// These are rendered on the corpse via `CorpseClothing` (0x89) but removed
/// from the container when the corpse is opened.
fn is_cosmetic_layer(layer: Layer) -> bool {
    matches!(layer, Layer::Hair | Layer::Beard | Layer::Face)
}

// ── Handler ──────────────────────────────────────────────────────────────

/// Atomically kill a mobile and create a lootable corpse.
///
/// See [`EngineCommand::KillMobile`](super::EngineCommand::KillMobile) for
/// the full description.
pub(super) fn handle_kill_mobile<P: ZoneItemProps>(
    zone: &mut Zone<DemoEntity, HashContainerStore, P>,
    event_tx: &tokio::sync::mpsc::UnboundedSender<WorldEvent>,
    serial_alloc: &Arc<SerialAllocator>,
    equipment_index: &mut HashMap<u32, u32>,
    serial: u32,
    extra_loot: Vec<LootItem>,
    corpse_name: Option<String>,
) -> Option<KillResult>
where
    P::Value: 'static,
{
    // 1. Read mobile data before removal.
    let entity = zone.get(serial)?;
    let m = entity.mobile()?;

    let body_graphic = m.graphic;
    let hue = m.color;
    let x = m.x;
    let y = m.y;
    let z = m.z;
    let direction = m.direction;
    let name = m.name.clone();
    let equipment = m.items.clone();

    // 2. Allocate corpse serial.
    let corpse_serial = serial_alloc.alloc_item()
        .expect("item serial space exhausted");

    // 3. Build corpse clothing entries (for `MobileKilled` event / `CorpseClothing` packet).
    //    Equipment items keep their ORIGINAL serials (matching real UO behaviour from logs).
    //    We also build the container item list for the lootable items.
    let mut corpse_clothing: Vec<(u8, u32, u16, u16)> = Vec::new();
    let mut container_items: Vec<ContainerItem> = Vec::new();

    for eq in &equipment {
        let layer = eq.layer;
        let layer_wire = layer.to_wire();
        let color = eq.color.unwrap_or(0);

        // All equipment goes into CorpseClothing for visual display.
        corpse_clothing.push((layer_wire, eq.serial, eq.graphic, color));

        // Lootable equipment goes into the container as grabbable items.
        // Cosmetic layers (hair, beard, face) are display-only.
        if !is_cosmetic_layer(layer) {
            container_items.push(ContainerItem {
                serial: eq.serial,
                graphic: eq.graphic,
                amount: 1,
                x: random_container_x(),
                y: random_container_y(),
                color,
                grid_index: None,
            });
        }
    }

    // Allocate a hair item serial for cosmetic hair on the corpse.
    // Hair needs a fresh serial for the CorpseClothing because the original
    // hair item doesn't exist as a standalone item.  We keep the original
    // serial in corpse_clothing (already added above) since the equipment
    // list includes hair items with their original serials.

    // 4. Add extra loot items (gold, drops, etc.) with freshly allocated serials.
    let mut loot_serials: Vec<u32> = Vec::new();
    for loot in &extra_loot {
        let item_serial = serial_alloc.alloc_item()
            .expect("item serial space exhausted");
        loot_serials.push(item_serial);
        container_items.push(ContainerItem {
            serial: item_serial,
            graphic: loot.graphic,
            amount: loot.amount,
            x: random_container_x(),
            y: random_container_y(),
            color: loot.color,
            grid_index: None,
        });
    }

    // 5. Remove the living mobile from the zone store.
    //    Un-index equipment first.
    for eq in &equipment {
        equipment_index.remove(&eq.serial);
    }
    zone.remove(serial);
    zone.item_props.remove(serial);

    // 6. Spawn the corpse as a persistent world item.
    let corpse_entity = DemoEntity::Item {
        serial: corpse_serial,
        graphic: CORPSE_GRAPHIC,
        color: hue,
        amount: body_graphic,
        x,
        y,
        z,
        is_container: true,
        hidden: false,
        facing: Some(direction & 0x07),
    };
    let corpse_pos = EngineEntity::pos(&corpse_entity);
    let corpse_snap = corpse_entity.snapshot();
    zone.spawn(corpse_serial, corpse_entity);

    // 7. Register the corpse container with all loot items.
    let container = ContainerInfo {
        serial: corpse_serial,
        gump_model: CORPSE_GUMP,
        items: container_items,
    };
    zone.containers.insert(corpse_serial, container);

    // 8. Set corpse item properties (name, corpse metadata).
    let display_name = corpse_name.unwrap_or_else(|| {
        if name.is_empty() {
            format!("a corpse")
        } else {
            format!("a corpse of {}", name)
        }
    });

    let mut props = ItemProps::with_name(&display_name);

    // Store corpse clothing data in meta so it can be re-sent when:
    // - A new observer walks into range and sees the corpse entity.
    // - A player double-clicks the corpse to open it.
    //
    // Format: JSON array of [layer_wire, item_serial, graphic, color] tuples.
    let clothing_json = serde_json::to_string(&corpse_clothing).unwrap_or_default();
    props.set_meta("corpse_clothing", MetaValue::Str(clothing_json));
    props.set_meta("body_graphic", MetaValue::Int(body_graphic as i64));

    zone.item_props.insert(corpse_serial, unsafe_cast_props::<P>(props));

    // Set item properties for extra loot items (display names).
    for (i, loot) in extra_loot.iter().enumerate() {
        if let Some(ref item_name) = loot.name {
            let item_props = ItemProps::with_name(item_name);
            zone.item_props.insert(loot_serials[i], unsafe_cast_props::<P>(item_props));
        }
    }

    // 9. Emit MobileKilled event (death animation + corpse clothing for
    //    currently connected observers).
    let _ = event_tx.send(WorldEvent::MobileKilled {
        map_id: zone.map_id,
        serial,
        body_graphic,
        hue,
        x,
        y,
        z,
        direction,
        corpse_serial,
        corpse_items: corpse_clothing,
    });

    // 10. Emit EntitySpawned for the corpse item so new observers will see it.
    //     (MobileKilled only sends transient packets to current observers.)
    let _ = event_tx.send(WorldEvent::EntitySpawned {
        map_id: zone.map_id,
        serial: corpse_serial,
        pos: corpse_pos,
        entity: corpse_snap,
    });

    // 11. Emit EntityRemoved for the living mobile.
    let _ = event_tx.send(WorldEvent::EntityRemoved {
        map_id: zone.map_id,
        serial,
        last_pos: corpse_pos,
    });

    Some(KillResult {
        corpse_serial,
        x,
        y,
        z,
        dropped_mount: None,
    })
}

// ── Kill player (ghost, no removal) ──────────────────────────────────────

/// Atomically kill a *player* and turn them into a ghost.
///
/// Unlike [`handle_kill_mobile`], the player mobile stays in the world.
/// Non-newbie equipment is moved to a corpse container; newbie items
/// (see [`is_newbie_item`]), the backpack, and cosmetic layers remain
/// equipped on the player.  The player's body becomes a ghost graphic,
/// `MobileData::dead` is set, and a death robe (burial shroud) is equipped.
///
/// If the player was mounted, the mount is removed from them entirely and the
/// original NPC is re-spawned beside the corpse from the data saved on the
/// mount item.  When no saved data exists, the mount item is returned in
/// [`KillResult::dropped_mount`] so the caller can spawn a default NPC.
///
/// Returns the corpse [`KillResult`], or `None` if the entity is missing,
/// not a mobile, or already dead.
pub(super) fn handle_kill_player<P: ZoneItemProps>(
    zone: &mut Zone<DemoEntity, HashContainerStore, P>,
    event_tx: &tokio::sync::mpsc::UnboundedSender<WorldEvent>,
    serial_alloc: &Arc<SerialAllocator>,
    equipment_index: &mut HashMap<u32, u32>,
    serial: u32,
) -> Option<KillResult>
where
    P::Value: 'static,
{
    // 1. Read mobile data before mutation.
    let entity = zone.get(serial)?;
    let m = entity.mobile()?;
    if m.dead {
        return None; // already a ghost
    }

    let body_graphic = m.graphic;
    let hue = m.color;
    let x = m.x;
    let y = m.y;
    let z = m.z;
    let direction = m.direction;
    let name = m.name.clone();
    let equipment = m.items.clone();

    let ghost_graphic = super::ghost_graphic_for(body_graphic);

    // 2. Partition equipment into "dropped to corpse" vs "kept (newbie)".
    //    Backpack and cosmetic layers always stay on the player.  The mount
    //    (if any) is removed from the player entirely and returned to the
    //    caller, which re-spawns the original mount NPC beside the corpse.
    let mut corpse_clothing: Vec<(u8, u32, u16, u16)> = Vec::new();
    let mut container_items: Vec<ContainerItem> = Vec::new();
    let mut kept_equipment: Vec<EquippedItem> = Vec::new();
    let mut dropped_mount: Option<EquippedItem> = None;
    let mut backpack_serial: Option<u32> = None;

    for eq in &equipment {
        let layer = eq.layer;
        let color = eq.color.unwrap_or(0);

        // The mount becomes a standalone NPC again — never on the corpse.
        if layer == Layer::Mount {
            dropped_mount = Some(eq.clone());
            continue;
        }

        // The backpack stays equipped, but its contents are looted below.
        if layer == Layer::Backpack {
            backpack_serial = Some(eq.serial);
            kept_equipment.push(eq.clone());
            continue;
        }

        // Newbie items and cosmetic layers stay equipped.
        let keep = is_cosmetic_layer(layer)
            || is_newbie_item::<P>(zone, eq.serial);

        if keep {
            kept_equipment.push(eq.clone());
            continue;
        }

        // Dropped equipment: shown on the corpse and lootable inside it.
        let layer_wire = layer.to_wire();
        corpse_clothing.push((layer_wire, eq.serial, eq.graphic, color));
        container_items.push(ContainerItem {
            serial: eq.serial,
            graphic: eq.graphic,
            amount: 1,
            x: random_container_x(),
            y: random_container_y(),
            color,
            grid_index: None,
        });
    }

    // 2b. Move the backpack's contents into the corpse, except newbie items
    //     (which stay in the player's backpack).  The backpack item itself
    //     remains equipped on the ghost.
    if let Some(bp) = backpack_serial {
        let (looted, kept_in_backpack): (Vec<ContainerItem>, Vec<ContainerItem>) =
            zone.containers.get(bp)
                .map(|info| info.items.clone())
                .unwrap_or_default()
                .into_iter()
                .partition(|item| !is_newbie_item::<P>(zone, item.serial));

        for item in looted {
            container_items.push(ContainerItem {
                serial: item.serial,
                graphic: item.graphic,
                amount: item.amount,
                x: random_container_x(),
                y: random_container_y(),
                color: item.color,
                grid_index: None,
            });
        }

        // Rewrite the backpack to keep only newbie items.
        if let Some(info) = zone.containers.get_mut(bp) {
            info.items = kept_in_backpack;
        }
    }

    // 3. Allocate corpse serial.
    let corpse_serial = serial_alloc.alloc_item()
        .expect("item serial space exhausted");

    // 3b. Equip a death robe (burial shroud) on the ghost.  It replaces any
    //     robe that was dropped to the corpse and is removed on resurrection.
    let death_robe = EquippedItem {
        serial: serial_alloc.alloc_item().expect("item serial space exhausted"),
        graphic: super::DEATH_ROBE_GRAPHIC,
        layer: Layer::Robe,
        color: None,
    };
    kept_equipment.push(death_robe.clone());

    // 4. Mutate the player mobile in place: ghost body, keep only newbie gear,
    //    mark dead, save the living graphic, and drop HP to 0.
    if let Some(m) = zone.store.get_mut(serial).and_then(|e| e.mobile_mut()) {
        // Un-index dropped equipment (including the mount).
        for eq in &equipment {
            if !kept_equipment.iter().any(|k| k.serial == eq.serial) {
                equipment_index.remove(&eq.serial);
            }
        }
        m.living_graphic = body_graphic;
        m.graphic = ghost_graphic;
        m.dead = true;
        m.hits = 0;
        m.items = kept_equipment;
    }
    // Index the death robe to its wearer.
    equipment_index.insert(death_robe.serial, serial);

    // 5. Spawn the corpse as a persistent world item.
    let corpse_entity = DemoEntity::Item {
        serial: corpse_serial,
        graphic: CORPSE_GRAPHIC,
        color: hue,
        amount: body_graphic,
        x,
        y,
        z,
        is_container: true,
        hidden: false,
        facing: Some(direction & 0x07),
    };
    let corpse_pos = EngineEntity::pos(&corpse_entity);
    let corpse_snap = corpse_entity.snapshot();
    zone.spawn(corpse_serial, corpse_entity);

    // 6. Register the corpse container with all dropped items.
    let container = ContainerInfo {
        serial: corpse_serial,
        gump_model: CORPSE_GUMP,
        items: container_items,
    };
    zone.containers.insert(corpse_serial, container);

    // 7. Set corpse item properties (name, clothing, owner).
    let display_name = if name.is_empty() {
        "a corpse".to_string()
    } else {
        format!("a corpse of {}", name)
    };
    let mut props = ItemProps::with_name(&display_name);
    let clothing_json = serde_json::to_string(&corpse_clothing).unwrap_or_default();
    props.set_meta("corpse_clothing", MetaValue::Str(clothing_json));
    props.set_meta("body_graphic", MetaValue::Int(body_graphic as i64));
    // Owner serial: used by resurrection to return items to the right player.
    props.set_meta("owner", MetaValue::Int(serial as i64));
    zone.item_props.insert(corpse_serial, unsafe_cast_props::<P>(props));

    // 8. Emit PlayerDied (death animation + corpse clothing for observers,
    //    and ghost body swap for the player's own session).
    let ghost_snap = zone.get(serial).and_then(|e| e.snapshot());
    let _ = event_tx.send(WorldEvent::PlayerDied {
        map_id: zone.map_id,
        serial,
        body_graphic,
        ghost_graphic,
        hue,
        x,
        y,
        z,
        direction,
        corpse_serial,
        corpse_items: corpse_clothing,
        entity: ghost_snap,
        mount_item_serial: dropped_mount.as_ref().map(|m| m.serial),
    });

    // 9. Emit EntitySpawned for the corpse so new observers will see it.
    let _ = event_tx.send(WorldEvent::EntitySpawned {
        map_id: zone.map_id,
        serial: corpse_serial,
        pos: corpse_pos,
        entity: corpse_snap,
    });

    // 10. If the player was mounted, restore the original mount NPC beside the
    //     corpse from the data saved on the mount item (see demo-server
    //     `mount.rs`).  If no saved entity is available, leave `dropped_mount`
    //     populated so the caller can spawn a default NPC from the graphic.
    let mut dropped_mount = dropped_mount;
    if let Some(ref mount) = dropped_mount {
        if let Some(npc_serial) = respawn_mount_npc_from_saved::<P>(
            zone, event_tx, serial_alloc, mount.serial, x, y, z,
        ) {
            // Clean up the mount item's props now that the NPC is back.
            zone.item_props.remove(mount.serial);
            let _ = npc_serial;
            dropped_mount = None; // handled by the engine
        }
    }

    Some(KillResult { corpse_serial, x, y, z, dropped_mount })
}

/// Restore a previously-saved mount NPC (stored on the mount item's
/// `meta["mount_npc_entity"]` as serialized JSON) beside the death location.
///
/// Allocates a fresh mobile serial, spawns the NPC adjacent to `(x, y, z)`,
/// and emits `EntitySpawned`.  Returns the new serial, or `None` if no saved
/// entity data exists (the caller then spawns a default NPC from the graphic).
fn respawn_mount_npc_from_saved<P: ZoneItemProps>(
    zone: &mut Zone<DemoEntity, HashContainerStore, P>,
    event_tx: &tokio::sync::mpsc::UnboundedSender<WorldEvent>,
    serial_alloc: &Arc<SerialAllocator>,
    mount_item_serial: u32,
    x: u16,
    y: u16,
    z: i8,
) -> Option<u32>
where
    P::Value: 'static,
{
    let json = props_as_item_props::<P>(zone.item_props.get(mount_item_serial))
        .and_then(|p| p.get_meta_str("mount_npc_entity"))?
        .to_string();

    let mut npc: DemoEntity = serde_json::from_str(&json).ok()?;

    let npc_serial = serial_alloc.alloc_mobile()?;
    if let Some(m) = npc.mobile_mut() {
        m.serial = npc_serial;
        // Place beside the death tile.
        m.x = x.wrapping_add(1);
        m.y = y;
        m.z = z;
    }

    let pos = EngineEntity::pos(&npc);
    let snap = npc.snapshot();
    zone.spawn(npc_serial, npc);

    let _ = event_tx.send(WorldEvent::EntitySpawned {
        map_id: zone.map_id,
        serial: npc_serial,
        pos,
        entity: snap,
    });

    Some(npc_serial)
}

// ── Resurrect player ─────────────────────────────────────────────────────

/// Resurrect a dead player (ghost) back to a living body.
///
/// Restores the living graphic, clears the dead flag, sets HP to
/// [`RESURRECT_HP`](super::RESURRECT_HP), and — if a corpse owned by this
/// player is within [`RESURRECT_LOOT_RANGE`](super::RESURRECT_LOOT_RANGE)
/// tiles — returns all corpse items (re-equipping using the saved layer map)
/// and removes the corpse.
///
/// Returns `true` if the player was resurrected, `false` if not found or not
/// currently dead.
pub(super) fn handle_resurrect<P: ZoneItemProps>(
    zone: &mut Zone<DemoEntity, HashContainerStore, P>,
    event_tx: &tokio::sync::mpsc::UnboundedSender<WorldEvent>,
    serial_alloc: &Arc<SerialAllocator>,
    equipment_index: &mut HashMap<u32, u32>,
    serial: u32,
) -> bool
where
    P::Value: 'static,
{
    let _ = serial_alloc; // kept for signature symmetry / future use

    // 1. Verify the player exists and is a dead mobile.
    let Some(entity) = zone.get(serial) else { return false };
    let Some(m) = entity.mobile() else { return false };
    if !m.dead {
        return false;
    }
    let (px, py) = (m.x, m.y);
    let restored_graphic = if m.living_graphic != 0 {
        m.living_graphic
    } else {
        // Fallback: assume male human.
        0x0190
    };
    // The player's backpack serial — loose corpse loot is returned here.
    let backpack_serial: Option<u32> = m.items.iter()
        .find(|i| i.layer == Layer::Backpack)
        .map(|i| i.serial);

    // 2. Look for an owned corpse within loot range to return items from.
    //    Collect candidate corpse serials first to avoid overlapping borrows.
    let candidate_corpses: Vec<u32> = zone.containers.containers().iter()
        .filter(|(_, info)| info.gump_model == CORPSE_GUMP)
        .map(|(&cs, _)| cs)
        .collect();

    let mut owned_corpse: Option<u32> = None;
    let mut owned_corpse_pos = EngineEntity::pos(zone.get(serial).unwrap());
    for cs in candidate_corpses {
        let is_owned = props_as_item_props::<P>(zone.item_props.get(cs))
            .and_then(|p| p.get_meta_int("owner"))
            .map(|o| o as u32 == serial)
            .unwrap_or(false);
        if !is_owned {
            continue;
        }
        if let Some(corpse) = zone.get(cs) {
            let cpos = EngineEntity::pos(corpse);
            let dist = chebyshev(px, py, cpos.x, cpos.y);
            if dist <= super::RESURRECT_LOOT_RANGE {
                owned_corpse = Some(cs);
                owned_corpse_pos = cpos;
                break;
            }
        }
    }

    // 3. Gather items + saved layer map from the corpse (if any in range).
    let mut returned_equipment: Vec<EquippedItem> = Vec::new();
    if let Some(cs) = owned_corpse {
        // Saved layer map: serial → (layer_wire, graphic, color).
        let clothing: Vec<(u8, u32, u16, u16)> =
            props_as_item_props::<P>(zone.item_props.get(cs))
                .and_then(|p| p.get_meta_str("corpse_clothing"))
                .and_then(|s| serde_json::from_str(s).ok())
                .unwrap_or_default();
        let layer_of: HashMap<u32, (u8, u16, u16)> = clothing
            .into_iter()
            .map(|(layer_wire, s, g, c)| (s, (layer_wire, g, c)))
            .collect();

        if let Some(info) = zone.containers.get(cs) {
            for item in &info.items {
                if let Some(&(layer_wire, graphic, color)) = layer_of.get(&item.serial) {
                    returned_equipment.push(EquippedItem {
                        serial: item.serial,
                        graphic,
                        layer: Layer::from_wire(layer_wire),
                        color: if color != 0 { Some(color) } else { None },
                    });
                }
            }
        }

        // Remove the re-equipped (worn) items from the corpse, and move all
        // remaining loose loot (former backpack contents) into the player's
        // backpack.  After this the corpse is empty and removed.
        //
        // IMPORTANT: mutate containers only via the index-maintaining API
        // (`remove_item_from`, `ingest_item_upsert`).  Touching `info.items`
        // directly bypasses the reverse index (`find_container_of_item`),
        // leaving moved items pointing at the now-deleted corpse — which makes
        // them "unknown" / "out of sight" to subsequent interactions.
        let returned_serials: std::collections::HashSet<u32> =
            returned_equipment.iter().map(|e| e.serial).collect();

        // Snapshot the corpse contents, then classify into worn (re-equipped)
        // vs loose loot.  Worn items leave for the mobile's equipment; loose
        // loot is moved into the backpack.
        let corpse_items: Vec<ContainerItem> = zone.containers
            .get(cs)
            .map(|info| info.items.clone())
            .unwrap_or_default();

        let mut moved_to_backpack: Vec<u32> = Vec::new();
        let mut removed_from_corpse: Vec<u32> = Vec::new();
        for item in corpse_items {
            // Remove from the corpse first (maintains the reverse index).
            zone.containers.remove_item_from(cs, item.serial);
            removed_from_corpse.push(item.serial);

            if returned_serials.contains(&item.serial) {
                // Worn item: returned via equipment, indexed below.
                continue;
            }

            // Loose loot: move into the player's backpack (if known).
            if let Some(bp) = backpack_serial {
                let mut item = item;
                item.x = random_container_x();
                item.y = random_container_y();
                item.grid_index = None;
                moved_to_backpack.push(item.serial);
                // Upsert into the backpack — updates the reverse index.
                zone.containers.ingest_item_upsert(bp, item);
            }
        }

        // Notify observers/owner that ALL items left the corpse.  This MUST
        // happen while the corpse is still a live world entity, otherwise
        // `resolve_container_position` cannot locate it and the event is
        // dropped (leaving stale items in the client's open corpse gump).
        if !removed_from_corpse.is_empty() {
            let changes: Vec<ContainerContentChange> = removed_from_corpse
                .iter()
                .map(|&s| ContainerContentChange::ItemRemoved { item_serial: s })
                .collect();
            super::item_ops::emit_container_event(
                zone, event_tx, equipment_index, cs, changes,
            );
        }

        // Notify the player's backpack listeners about the looted items.
        // Also emitted while the backpack is live (equipped on the mobile).
        if let Some(bp) = backpack_serial {
            if !moved_to_backpack.is_empty() {
                let added: Vec<ContainerContentChange> = moved_to_backpack
                    .iter()
                    .filter_map(|&s| {
                        zone.containers.get(bp)
                            .and_then(|info| info.items.iter().find(|i| i.serial == s))
                            .map(|i| ContainerContentChange::ItemAdded {
                                item_serial: i.serial,
                                graphic: i.graphic,
                                amount: i.amount,
                                x: i.x,
                                y: i.y,
                                color: i.color,
                            })
                    })
                    .collect();
                super::item_ops::emit_container_event(
                    zone, event_tx, equipment_index, bp, added,
                );
            }
        }

        // The corpse is now empty — remove it entirely.  Emit EntityRemoved
        // last so the client deletes the (now-empty) corpse object after it
        // has processed the item-removal events above.
        zone.containers.remove(cs);
        zone.remove(cs);
        zone.item_props.remove(cs);
        let _ = event_tx.send(WorldEvent::EntityRemoved {
            map_id: zone.map_id,
            serial: cs,
            last_pos: owned_corpse_pos,
        });
    }

    // 4. Restore the living body, HP, and re-equip returned items.
    let mut removed_robe_serials: Vec<u32> = Vec::new();
    let (rx, ry, rz, rdir, rhue, new_hits, max_hits) = {
        let Some(m) = zone.store.get_mut(serial).and_then(|e| e.mobile_mut()) else {
            return false;
        };
        m.graphic = restored_graphic;
        m.living_graphic = 0;
        m.dead = false;
        // Clear the hidden bit (0x80) set while the player was an invisible
        // ghost — otherwise the resurrected body is drawn hidden (grey/
        // translucent) on the player's own client.
        m.status = packets::mobile_flags::MobileFlags(m.status.0 & !0x80);
        m.hits = super::RESURRECT_HP.min(m.hits_max.max(super::RESURRECT_HP));
        // Remove the death robe equipped on death (burial shroud).
        m.items.retain(|i| {
            if i.layer == Layer::Robe && i.graphic == super::DEATH_ROBE_GRAPHIC {
                removed_robe_serials.push(i.serial);
                false
            } else {
                true
            }
        });
        for eq in &returned_equipment {
            // Avoid duplicates if somehow already present.
            if !m.items.iter().any(|i| i.serial == eq.serial) {
                m.items.push(eq.clone());
            }
        }
        (m.x, m.y, m.z, m.direction, m.color, m.hits, m.hits_max)
    };

    // Un-index the removed death robe.
    for s in &removed_robe_serials {
        equipment_index.remove(s);
    }

    // Re-index returned equipment.
    for eq in &returned_equipment {
        equipment_index.insert(eq.serial, serial);
    }

    // 5. Emit PlayerResurrected.
    let living_snap = zone.get(serial).and_then(|e| e.snapshot());
    let _ = event_tx.send(WorldEvent::PlayerResurrected {
        map_id: zone.map_id,
        serial,
        body_graphic: restored_graphic,
        hue: rhue,
        x: rx,
        y: ry,
        z: rz,
        direction: rdir,
        new_hits,
        max_hits,
        entity: living_snap,
    });

    true
}

/// Returns `true` if the item carries `meta["newbie"] == true`.
fn is_newbie_item<P: ZoneItemProps>(
    zone: &Zone<DemoEntity, HashContainerStore, P>,
    item_serial: u32,
) -> bool
where
    P::Value: 'static,
{
    props_as_item_props::<P>(zone.item_props.get(item_serial))
        .and_then(|p| p.get_meta_bool("newbie"))
        .unwrap_or(false)
}

/// Chebyshev (chessboard) distance between two tile positions.
fn chebyshev(x1: u16, y1: u16, x2: u16, y2: u16) -> u16 {
    let dx = (x1 as i32 - x2 as i32).unsigned_abs() as u16;
    let dy = (y1 as i32 - y2 as i32).unsigned_abs() as u16;
    dx.max(dy)
}

/// Downcast a generic `&P::Value` to `&ItemProps`, if the concrete value
/// type is actually `ItemProps` (always true for the demo-server).
fn props_as_item_props<P: ZoneItemProps>(value: Option<&P::Value>) -> Option<&ItemProps>
where
    P::Value: 'static,
{
    let v = value?;
    (v as &dyn std::any::Any).downcast_ref::<ItemProps>()
}

// ── Add items to existing container ──────────────────────────────────────

/// Add loot items to an existing container (e.g. a corpse created by auto-kill).
///
/// Allocates serials for each item, inserts them into the container store,
/// and emits `ContainerContentsUpdated` so clients see the new items.
pub(super) fn handle_add_container_items<P: ZoneItemProps>(
    zone: &mut Zone<DemoEntity, HashContainerStore, P>,
    event_tx: &tokio::sync::mpsc::UnboundedSender<WorldEvent>,
    serial_alloc: &Arc<SerialAllocator>,
    equipment_index: &HashMap<u32, u32>,
    container_serial: u32,
    items: Vec<LootItem>,
) where
    P::Value: 'static,
{
    if items.is_empty() {
        return;
    }

    let mut changes = Vec::new();

    for loot in &items {
        let item_serial = serial_alloc.alloc_item()
            .expect("item serial space exhausted");

        let x = random_container_x();
        let y = random_container_y();

        let ci = ContainerItem {
            serial: item_serial,
            graphic: loot.graphic,
            amount: loot.amount,
            x,
            y,
            color: loot.color,
            grid_index: None,
        };

        zone.containers.ingest_item_upsert(container_serial, ci);

        changes.push(ContainerContentChange::ItemUpdated {
            item_serial,
            graphic: loot.graphic,
            amount: loot.amount,
            x,
            y,
            color: loot.color,
        });

        // Set item props (name).
        if let Some(ref item_name) = loot.name {
            let item_props = ItemProps::with_name(item_name);
            zone.item_props.insert(item_serial, unsafe_cast_props::<P>(item_props));
        }
    }

    // Emit container update event.
    super::item_ops::emit_container_event(
        zone, event_tx, equipment_index,
        container_serial, changes,
    );
}

// ── Helpers ──────────────────────────────────────────────────────────────

/// Random gump-relative X coordinate for an item inside a corpse container.
fn random_container_x() -> u16 {
    use rand::Rng;
    rand::rng().random_range(20..=120)
}

/// Random gump-relative Y coordinate for an item inside a corpse container.
fn random_container_y() -> u16 {
    use rand::Rng;
    rand::rng().random_range(80..=160)
}

/// Cast `ItemProps` to the generic `P::Value` type.
///
/// This is safe as long as the zone's `ZoneItemProps` implementation
/// actually stores `ItemProps` values — which is the case for the
/// demo-server.  The framework uses generic type parameters for
/// flexibility, but in practice this is always `ItemProps`.
fn unsafe_cast_props<P: ZoneItemProps>(props: ItemProps) -> P::Value
where
    P::Value: 'static,
{
    let any: Box<dyn std::any::Any> = Box::new(props);
    *any.downcast::<P::Value>().expect("ZoneItemProps::Value must be ItemProps")
}
