[package]
name = "simple-proxy"
version = "0.1.0"
edition = "2024"
publish.workspace = true

[[bin]]
name = "simple-proxy"
path = "main.rs"

[dependencies]
u-core = { path = "../../u-core" }
network = { path = "../../network" }
protocol = { path = "../../protocol" }
packets = { path = "../../packets" }
common = { path = "../common" }
tokio = { version = "1.51.1", features = ["full"] }
async-trait = "0.1.89"
log = "0.4"
